### ISSUE TITLE
Error with make-probes if fasta file in lower case

### ISSUE THREAD

**Issue by jhawkey** [Mykrobe-tools/mykrobe#100]
Mykrobe's make-probes command doesn't seem to like it if you give it a fasta file that is lowercase. This error doesn't appear if you give it a fasta file with capital letters so it is an easy fix for the user at least. Error reproduced below:

```
mykrobe variants make-probes -t sonnei_QRDR_AA.txt -g NC_016822_v2.gbk NC_016822.fasta > test_probes.fa

[mykrobe 2020-09-17T04:33:18 WARNING] Could not connect to database. Continuing without using genetic backgrounds
Traceback (most recent call last):
File "/home/ubuntu/miniconda3/envs/mykrobe_new/bin/mykrobe", line 8, in <module>
sys.exit(main())
File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/cli.py", line 8, in main
args.func(parser, args)
File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/parser.py", line 54, in run_subtool
run(parser, args)
File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/cmds/makeprobes.py", line 63, in run
for var_name in aa2dna.get_variant_names(
File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/annotation/genes/models.py", line 185, in get_variant_names
return self._process_coding_mutation(gene, ref, start, alt)
File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/annotation/genes/models.py", line 219, in _process_coding_mutation
ref_codons = gene.get_reference_codons(start)
File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/annotation/genes/models.py", line 87, in get_reference_codons
ref_aa = standard_table.forward_table[str(ref_codon)]
KeyError: 'tcg'
```

**Comment by martinghunt** [comment]
Thanks for reporting this. I just fixed it so when it loads in the FASTA file it converts everything to uppercase.
