### ISSUE TITLE
make-probes ValueError

### ISSUE THREAD

**Issue by jhawkey** [Mykrobe-tools/mykrobe#101]
When attempting to make custom probes using mykrobe's in built make-probes function, I came across this error. Not sure the best way to tackle it.

All files used in this command can be found in the email I sent you.

```
mykrobe variants make-probes -t lineage_071020_JH.txt --lineage lineage_testOct.json -g ../ref_seqs/NC_016822_v2.gbk ../ref_seqs/NC_016822.fasta > lineage_probes_testOct.fa
[mykrobe 2020-10-07T04:30:56 WARNING] Could not connect to database. Continuing without using genetic backgrounds
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mykrobe_new/bin/mykrobe", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/parser.py", line 54, in run_subtool
    run(parser, args)
  File "/home/ubuntu/miniconda3/envs/mykrobe_new/lib/python3.8/site-packages/mykrobe/cmds/makeprobes.py", line 58, in run
    gene, mutation_string, alphabet = row
ValueError: too many values to unpack (expected 3)
```

**Comment by martinghunt** [comment]
I'm not sure what's in `lineage_071020_JH.txt`, but I'm guessing a mix of DNA and PROT variants. I can reproduce this if I have a file of DNA only variants and use the `-g` option. The workaround is to run the command twice:
1. with only DNA variants, and do not use `-g`.
2. with only PROT variants, and do use `-g`.
