### ISSUE TITLE
Strange error with --ont flag

### ISSUE THREAD

**Issue by iqbal-lab** [Mykrobe-tools/mykrobe#123]
Jane Hawkey found a strange error when running with --ont flag. Pasting her email below

I’m having some issues using the ont flag - I keep getting the following error:

[mykrobe 2021-04-08T04:27:15 WARNING] Setting ploidy to haploid
[mykrobe 2021-04-08T04:27:15 WARNING] Setting ignore_minor_calls to True
[mykrobe 2021-04-08T04:27:15 WARNING] Setting expected error rate to 0.15 (--ont)
Traceback (most recent call last):
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/bin/mykrobe", line 8, in <module>
 sys.exit(main())
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/cli.py", line 8, in main
 args.func(parser, args)
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/parser.py", line 55, in run_subtool
 run(parser, args)
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/cmds/amr.py", line 396, in run
 gt.run()
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/typing/typer/genotyper.py", line 305, in run
 self._type()
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/typing/typer/genotyper.py", line 308, in _type
 self._type_genes()
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/typing/typer/genotyper.py", line 318, in _type_genes
 self.gene_presence_covgs[gene_name] = gt.type(
 File "/home/ubuntu/miniconda3/envs/mykrobe_typhi/lib/python3.9/site-packages/mykrobe/typing/typer/presence.py", line 151, in type
 sequence_coverage_collection.values(),
AttributeError: 'list' object has no attribute 'values'

If I run the reads without the ont flag, then mykrobe completes without error (but obviously gives weird results).

I have also tried without the ont flag, but on the command line set ploidy to haploid, expected_error_rate to 0.15 and provided the ignore_minor_calls flag (based on the logs it seems like this is what the ont flag is doing?). When I do this then mykrobe completes successfully.

I’ve tried a few different sets of ONT reads, and always get the same issue. Unfortunately I’m not able to share the private ONT data I have, but I have tried it on some publicly available ONT genomes! The error above was generated using read accession ERR4245161. All of the reads in bioproject PRJEB38900 are Typhi ONT.

**Comment by iqbal-lab** [comment]
@martinghunt has been debugging and partially understands what is going on. I'm raising this so we have a placeholder, and also to warn @mbhall88 that this is being fixed.
