### ISSUE TITLE
OS error

### ISSUE THREAD

**Issue by Bio-finder** [Mykrobe-tools/mykrobe#151]
Good morning, 
I have just installed your tool and I started to run a test but I bumped into an error that seems OS related. I am currently working on an Ubuntu LST 24.0 server and here is the error that I got:

` mykrobe predict --sample my_sample_name \
>   --species tb \
>   --output out.json \
>   --format json \
>   --seq reads.fq.gz
[mykrobe 2022-03-29T11:45:12 INFO] Start runnning mykrobe predict. Command line: /home/bebergk/.local/bin/mykrobe predict --sample my_sample_name --species tb --output out.json --format json --seq reads.fq.gz
[mykrobe 2022-03-29T11:45:12 INFO] Running mykrobe predict using species tb, and panel version 20201014
[mykrobe 2022-03-29T11:45:12 INFO] Run command: /home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex31 build -q -m 1GB -t 1 -k 21 -s tb-species-170421-tb-hunt-probe-set-jan-03-2019-tb -1 /home/bebergk/.local/lib/python3.8/site-packages/mykrobe/data/tb/tb-species-170421.fasta.gz -1 /home/bebergk/.local/lib/python3.8/site-packages/mykrobe/data/tb/tb-hunt-probe-set-jan-03-2019.fasta.gz -1 /home/bebergk/.local/lib/python3.8/site-packages/mykrobe/data/tb/tb.lineage.20200930.probes.fa.gz mykrobe/data/skeletons/tb-species-170421-tb-hunt-probe-set-jan-03-2019-tb_21.ctx
Traceback (most recent call last):
  File "/home/bebergk/.local/bin/mykrobe", line 8, in <module>
    sys.exit(main())
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cli.py", line 9, in main
    args.func(parser, args)
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/parser.py", line 53, in run_subtool
    run(parser, args)
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cmds/amr.py", line 290, in run
    cp.run()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/typing/typer/genotyper.py", line 74, in run
    self._run_cortex()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/typing/typer/genotyper.py", line 91, in _run_cortex
    self.mc_cortex_runner.run()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex.py", line 192, in run
    self._run_cortex()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex.py", line 207, in _run_cortex
    self._build_panel_binary_if_required()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex.py", line 225, in _build_panel_binary_if_required
    syscall(cmd)
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex.py", line 20, in syscall
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex31'
`

I saw that mccortex31 seems to be a binary file so could it be that it's compiled with a specific OS?
Best regards,

**Comment by mbhall88** [comment]
How did you install mykrobe?

**Comment by Bio-finder** [comment]
Hi,
I have installed it by cloning the repo and using the following  command line in the mykrobe repo folder: `pip3 install . && mykrobe panels update_metadata && mykrobe panels update_species all`

**Comment by Bio-finder** [comment]
I have also tried to install from source (from the  file  `mykrobe-0.10.0.tar.gz`)

and here, the file mccortex31 is missing:

` mykrobe predict --sample my_sample_name \
>   --species tb \
>   --output out.json \
>   --format json \
>   --seq reads.fq.gz
[mykrobe 2022-03-30T11:37:42 INFO] Start runnning mykrobe predict. Command line: /home/bebergk/.local/bin/mykrobe predict --sample my_sample_name --species tb --output out.json --format json --seq reads.fq.gz
[mykrobe 2022-03-30T11:37:42 INFO] Running mykrobe predict using species tb, and panel version 20201014
Traceback (most recent call last):
  File "/home/bebergk/.local/bin/mykrobe", line 8, in <module>
    sys.exit(main())
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/parser.py", line 53, in run_subtool
    run(parser, args)
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cmds/amr.py", line 285, in run
    cp.run()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/typing/typer/genotyper.py", line 73, in run
    self._run_cortex()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/typing/typer/genotyper.py", line 77, in _run_cortex
    self.mc_cortex_runner = McCortexGenoRunner(
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex.py", line 172, in __init__
    super(McCortexGenoRunner, self).__init__()
  File "/home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex.py", line 51, in __init__
    raise RuntimeError(f"Did not find mccortex31. Expected it to be here: {self.mccortex31_path}. Cannot continue")
RuntimeError: Did not find mccortex31. Expected it to be here: /home/bebergk/.local/lib/python3.8/site-packages/mykrobe/cortex/mccortex31. Cannot continue
`
So I don't get the same error as the git repo when I use the tar.gz file

**Comment by martinghunt** [comment]
Could you try the installation notes on what to do if mccortex is not found? Here's a copy of the notes:

If you get installation problems relating to compiling `mccortex`, then it may be helpful
to debug by trying to compile `mccortex` first. The `mykrobe` install looks for
the compiled binary file `./mccortex/bin/mccortex31`, and if it finds it then
it does not try to recompile, and simply copies the file.
This means you can make this binary before running `pip3`, like this:
```sh
git clone --recursive -b geno_kmer_count https://github.com/Mykrobe-tools/mccortex mccortex
cd mccortex
make
```
and once the `make` runs successfully, `pip3 install .` can be run from the `mykrobe/`
directory.

**Comment by Bio-finder** [comment]
the compiling of `mccortex` worked without any issues so I don't get why I am in so many troubles when installing from source. I would like ideally be able to compile mccortex in the pip install as I will deploy it on multiple VMs using ansible (automated deployment tool). I am not sure if on compiled tool would thus work for all the VM that I will use.

**Comment by mbhall88** [comment]
Mykrobe *should* compile `mccortex` during the install...

@Bio-finder would you mind trying the pip install method you were originally trying with verbose output on (`-vvv`) and send thorugh the log?

**Comment by martinghunt** [comment]
I think the cause might be that the `mccortex31` binary was accidentally added to the repo (commit afa500efd63cd0b2fa75f0b2f0fa564c4d3f3ed1).

@Bio-finder could you try deleting `src/mykrobe/cortex/mccortex31` and see if that stops the error?

**Comment by mbhall88** [comment]
Closing due to inactivity. Please reopen if you're still experiencing issues
