### ISSUE TITLE
python 2.7 help command fails

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#42]
Trying to run `mykrobe --help` in python 2.7 leads to error

```
Traceback (most recent call last):
  File "/Users/mbhall88/.local/share/virtualenvs/tmp-MliNr5iM/bin/mykrobe", line 11, in <module>
    load_entry_point('mykrobe', 'console_scripts', 'mykrobe')()
  File "/Users/mbhall88/.local/share/virtualenvs/tmp-MliNr5iM/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mbhall88/.local/share/virtualenvs/tmp-MliNr5iM/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/mbhall88/.local/share/virtualenvs/tmp-MliNr5iM/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/mbhall88/.local/share/virtualenvs/tmp-MliNr5iM/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mbhall88/Projects/mykrobe/src/mykrobe/cli.py", line 3, in <module>
    from mykrobe.parser import parser
  File "/Users/mbhall88/Projects/mykrobe/src/mykrobe/parser.py", line 141, in <module>
    help="build variant probes", aliases=['vars'])
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1066, in add_parser
    parser = self._parser_class(**kwargs)
  File "/Users/mbhall88/Projects/mykrobe/src/mykrobe/parser.py", line 45, in __init__
    super(ArgumentParserWithDefaults, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases'
```

It seems that `add_parser` does not take an `aliases` argument in python 2.7. See https://bugs.python.org/issue13879 for an example.

A possible fix could be https://gist.github.com/sampsyo/471779  

I would also suggest maybe adding some commands to test that the mykrobe commands all run the `--help` flag correctly. i.e
```
mykrobe --help
mykrobe predict --help
mykrobe variants --help
mykrobe genotype --help
```

**Comment by mbhall88** [comment]
@Phelimb I'll close this as I believe we aren't supporting python2 anymore? If that is incorrect feel free to reopen.
