### ISSUE TITLE
Panel data not visible to mykrobe in conda package

### ISSUE THREAD

**Issue by mbhall88** [Mykrobe-tools/mykrobe#46]
When trying to run mykrobe from the conda recipe am getting the following error:
```
INFO:mykrobe.cmds.amr:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-hunt-probe-set-jan-03-2019.fasta.gz
Traceback (most recent call last):
  File "/usr/local/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.7/site-packages/mykrobe/parser.py", line 40, in run_subtool
    run(parser, args)
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cmds/amr.py", line 256, in run
    cp.run()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/typing/typer/genotyper.py", line 73, in run
    self._run_cortex()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/typing/typer/genotyper.py", line 90, in _run_cortex
    self.mc_cortex_runner.run()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cortex/mccortex.py", line 183, in run
    self._check_panels()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cortex/mccortex.py", line 195, in _check_panels
    panel.filepath)
ValueError: Could not find a panel at /usr/local/lib/python3.7/site-packages/mykrobe/data/panels/tb-species-170421.fasta.gz.
```
This would indicate that the way that the data is downloaded and included in the [post-link script](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mykrobe/post-link.sh) is not working as expected/intended.

**Comment by mbhall88** [comment]
Raised https://github.com/bioconda/bioconda-recipes/issues/13784

**Comment by mbhall88** [comment]
Have confirmed the `conda` version is now working as expected.
