### ISSUE TITLE
installation issues - Centos 7

### ISSUE THREAD

**Issue by sagrudd** [Mykrobe-tools/mykrobe#78]
Hi folks,
I use Centos7 and have experienced a couple of issues with coercing mykrobe to install

1. Conda install fails with missing shasum errors - shasum is not a standard binary on Centos
2. Standard pip install does not run (as documented in https://github.com/Mykrobe-tools/mykrobe/issues/64)
3. pipenv install (Python 3.8.1 | packaged by conda-forge) gives /home/stephen/mykrobe/src/mykrobe/metagenomics/phylo.py:167: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  ) for subc in self.hierarchy.dict[pg]["children"].keys() if subc is not "Unknown"])

Have reverted to an Ubuntu installation for some different errors

**Comment by martinghunt** [comment]
Thanks for reporting. I'm going to fix number 2.

@mbhall88 I'm wondering if you have any thoughts on the conda issues?

**Comment by mbhall88** [comment]
@sagrudd could you please provide the log for your failed conda install?

**Comment by sagrudd** [comment]
@mbhall88 - here is the console output from ```conda install -c bioconda mykrobe```

I have tried aliasing shasum -> sha256sum but this still gives the same errors - eager to get started with some kykrobe based explorations - thanks for the assistance and input here

Cheers

S

```
(base) [stephen@R720-SIN ~]$ conda install -c bioconda mykrobe
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/stephen/miniconda3

  added / updated specs:
    - mykrobe


The following NEW packages will be INSTALLED:

  biopython          conda-forge/linux-64::biopython-1.76-py37h516909a_0
  cython             conda-forge/linux-64::cython-0.29.14-py37he1b5a44_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  krb5               conda-forge/linux-64::krb5-1.16.4-h2fd8d38_0
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libcurl            conda-forge/linux-64::libcurl-7.65.3-hda55be3_0
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libidn2            conda-forge/linux-64::libidn2-2.3.0-h516909a_0
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  libunistring       conda-forge/linux-64::libunistring-0.9.10-h14c3975_0
  mongodb            pkgs/main/linux-64::mongodb-4.0.3-h597af5e_0
  mongoengine        conda-forge/linux-64::mongoengine-0.19.1-py37_0
  mykrobe            bioconda/linux-64::mykrobe-0.7.0-py37ha80c686_2
  numpy              conda-forge/linux-64::numpy-1.17.3-py37h95a1406_0
  pymongo            conda-forge/linux-64::pymongo-3.10.1-py37he1b5a44_0
  pyvcf              conda-forge/linux-64::pyvcf-0.6.8-py37_1000
  wget               conda-forge/linux-64::wget-1.20.1-h22169c7_0

The following packages will be UPDATED:

  conda                                        4.8.0-py37_0 --> 4.8.0-py37_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: | b'ERROR: post-link.sh was unable to download any of the following URLs with the shasum 14b4e111d8b17a43dd30e3a55416bab79794ed56c44acc6238e1fd10addd0a03:\nhttps://bit.ly/2H9HKTU\n'                                                                                                                                                                done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::mykrobe-0.7.0-py37ha80c686_2'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::mykrobe-0.7.0-py37ha80c686_2
location of failed script: /home/stephen/miniconda3/bin/.mykrobe-post-link.sh
==> script messages <==
ERROR: post-link.sh was unable to download any of the following URLs with the shasum 14b4e111d8b17a43dd30e3a55416bab79794ed56c44acc6238e1fd10addd0a03:
https://bit.ly/2H9HKTU

==> script output <==
stdout:
stderr: --2020-01-14 07:55:56--  https://bit.ly/2H9HKTU
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.dropbox.com/s/sy4txy6l6lnmsem/mykrobe-data.tar.gz?dl=1 [following]
--2020-01-14 07:55:56--  https://www.dropbox.com/s/sy4txy6l6lnmsem/mykrobe-data.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:6022:1::a27d:4201, 162.125.66.1
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:6022:1::a27d:4201|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/sy4txy6l6lnmsem/mykrobe-data.tar.gz [following]
--2020-01-14 07:55:56--  https://www.dropbox.com/s/dl/sy4txy6l6lnmsem/mykrobe-data.tar.gz
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com/cd/0/get/AwIj9mTdP4axnghdSg3S4_bmv2ADQR5gBs2dXPpnUYUYvemK-SSX8AZTwaHTSZC0e7V4qSqiJjNd3VLc0eNA5irMpfk8nyj9onPlo0Z3smXq3w/file?dl=1# [following]
--2020-01-14 07:55:57--  https://uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com/cd/0/get/AwIj9mTdP4axnghdSg3S4_bmv2ADQR5gBs2dXPpnUYUYvemK-SSX8AZTwaHTSZC0e7V4qSqiJjNd3VLc0eNA5irMpfk8nyj9onPlo0Z3smXq3w/file?dl=1
Resolving uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com (uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com)... 2620:100:6022:6::a27d:4206, 162.125.66.6
Connecting to uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com (uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com)|2620:100:6022:6::a27d:4206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35842381 (34M) [application/binary]
Saving to: ‘STDOUT’

     0K .......... .......... .......... .......... ..........  0% 1.48M 23s
    50K .......... .......... .......... .......... ..........  0% 6.71M 14s
   100K .......... .......... .......... .......... ..........  0% 4.45M 12s

34850K .......... .......... .......... .......... .......... 99% 13.1M 0s
 34900K .......... .......... .......... .......... .......... 99% 13.1M 0s
 34950K .......... .......... .......... .......... .......... 99% 14.7M 0s
 35000K ..                                                    100% 4435G=2.8s

2020-01-14 07:56:00 (12.4 MB/s) - written to stdout [35842381/35842381]

/home/stephen/miniconda3/bin/.mykrobe-post-link.sh: line 16: shasum: command not found

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1078, in __call__
    return func(*args, **kwargs)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 346, in handle_txn
    unlink_link_transaction.execute()
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 249, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 716, in _execute
    rollback_excs,
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::mykrobe-0.7.0-py37ha80c686_2
location of failed script: /home/stephen/miniconda3/bin/.mykrobe-post-link.sh
==> script messages <==
ERROR: post-link.sh was unable to download any of the following URLs with the shasum 14b4e111d8b17a43dd30e3a55416bab79794ed56c44acc6238e1fd10addd0a03:
https://bit.ly/2H9HKTU

==> script output <==
stdout:
stderr: --2020-01-14 07:55:56--  https://bit.ly/2H9HKTU
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.dropbox.com/s/sy4txy6l6lnmsem/mykrobe-data.tar.gz?dl=1 [following]
--2020-01-14 07:55:56--  https://www.dropbox.com/s/sy4txy6l6lnmsem/mykrobe-data.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:6022:1::a27d:4201, 162.125.66.1
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:6022:1::a27d:4201|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/sy4txy6l6lnmsem/mykrobe-data.tar.gz [following]
--2020-01-14 07:55:56--  https://www.dropbox.com/s/dl/sy4txy6l6lnmsem/mykrobe-data.tar.gz
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com/cd/0/get/AwIj9mTdP4axnghdSg3S4_bmv2ADQR5gBs2dXPpnUYUYvemK-SSX8AZTwaHTSZC0e7V4qSqiJjNd3VLc0eNA5irMpfk8nyj9onPlo0Z3smXq3w/file?dl=1# [following]
--2020-01-14 07:55:57--  https://uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com/cd/0/get/AwIj9mTdP4axnghdSg3S4_bmv2ADQR5gBs2dXPpnUYUYvemK-SSX8AZTwaHTSZC0e7V4qSqiJjNd3VLc0eNA5irMpfk8nyj9onPlo0Z3smXq3w/file?dl=1
Resolving uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com (uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com)... 2620:100:6022:6::a27d:4206, 162.125.66.6
Connecting to uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com (uc17607193e1df5b56490d396e0f.dl.dropboxusercontent.com)|2620:100:6022:6::a27d:4206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35842381 (34M) [application/binary]
Saving to: ‘STDOUT’

     0K .......... .......... .......... .......... ..........  0% 1.48M 23s
    50K .......... .......... .......... .......... ..........  0% 6.71M 14s
   100K .......... .......... .......... .......... ..........  0% 4.45M 12s
   150K .......... .......... .......... .......... ..........  0% 8.04M 10s

...

34850K .......... .......... .......... .......... .......... 99% 13.1M 0s
 34900K .......... .......... .......... .......... .......... 99% 13.1M 0s
 34950K .......... .......... .......... .......... .......... 99% 14.7M 0s
 35000K ..                                                    100% 4435G=2.8s

2020-01-14 07:56:00 (12.4 MB/s) - written to stdout [35842381/35842381]

/home/stephen/miniconda3/bin/.mykrobe-post-link.sh: line 16: shasum: command not found

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1370, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1081, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1112, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1128, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1132, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1055, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/home/stephen/miniconda3/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/stephen/miniconda3/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/home/stephen/miniconda3/lib/python3.7/logging/__init__.py", line 1528, in handle
    if (not self.disabled) and self.filter(record):
  File "/home/stephen/miniconda3/lib/python3.7/logging/__init__.py", line 762, in filter
    result = f.filter(record)
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/gateways/logging.py", line 60, in filter
    record.msg = record.msg % new_args
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/__init__.py", line 123, in __repr__
    errs.append(e.__repr__())
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/__init__.py", line 62, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/home/stephen/miniconda3/lib/python3.7/site-packages/conda/__init__.py", line 81, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'M' (0x4d) at index 2260
```

**Comment by mbhall88** [comment]
@sagrudd so to be clear, you have `sha256sum` available on your centOS but not `shasum`?

**Comment by sagrudd** [comment]
@mbhall88 - I have ```sha1sum    sha224sum  sha256sum  sha384sum  sha512sum``` - there is no ```shasum```

**Comment by mbhall88** [comment]
@sagrudd could you please try installing from conda again? I have updated the build process and it should check for either `sha256sum` or `shasum` now.

**Comment by sagrudd** [comment]
@mbhall88 - great stuff - thanks! The conda install on Centos worked like a charm ... installed the package that you mentioned above ```mykrobe            bioconda/linux-64::mykrobe-0.7.0-py36ha80c686_3
``` - ready for testing now ...  Thanks for the assistance
