### ISSUE TITLE
UnboundLocalError for staph panel

### ISSUE THREAD

**Issue by esteinig** [Mykrobe-tools/mykrobe#88]
Version: 0.8.1 installed from `BioConda` inside a Singularity container. Essentially `conda install -c bioconda -conda-forge mykrobe`

I am getting a variable reference error when running the `staph` option:

```
container.sif mykrobe predict test staph --seq test.fq
```

leads to:

```
Traceback (most recent call last):                                                                                                                                                                                
  File "/opt/conda/bin/mykrobe", line 11, in                                                                                                                                                              
    sys.exit(main())                                                                                                                                                                                              
  File "/opt/conda/lib/python3.7/site-packages/mykrobe/cli.py", line 8, in main                                                                                                                                   
    args.func(parser, args)                                                                                                                                                                                       
  File "/opt/conda/lib/python3.7/site-packages/mykrobe/parser.py", line 42, in run_subtool                                                                                                                        
    run(parser, args)                                                                                                                                                                                             
  File "/opt/conda/lib/python3.7/site-packages/mykrobe/cmds/amr.py", line 293, in run                                                                                                                             
    panels = STAPH_PANELS                                                                                                                                                                                         
UnboundLocalError: local variable 'STAPH_PANELS' referenced before assignment
```

**Comment by esteinig** [comment]
thanks a bunch @mbhall88 i saw there are gram negative panels as well - are they functional?

**Comment by mbhall88** [comment]
@iqbal-lab or @martinghunt are probably better qualified to answer that.

They exist. But the CLI seems to be set up to not allow the user to enter `gn` as a species.

**Comment by iqbal-lab** [comment]
Apologies @esteinig @mbhall88  - we did a long time ago start making a gram negative panel, but discarded. if it's still in the repo, we should remove. Mykrobe now does support genotyping of your own panel, so you can pass in your own GN panel if you like, and then parse the genotyped output (yes we do see this allele) into a prediction if you like
